//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsCEConsentForms.OutsideOR {
    
    
    public partial class Declaration {
        
        /// <summary>
        /// PatientDetails1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WindowsCEConsentForms.PatientDetails PatientDetails1;
        
        /// <summary>
        /// DoctorsAndProcedures1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WindowsCEConsentForms.DoctorsAndProcedures DoctorsAndProcedures1;
        
        /// <summary>
        /// ConsentSignatures1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WindowsCEConsentForms.ConsentSignatures ConsentSignatures1;
        
        /// <summary>
        /// DeclarationSignatures1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WindowsCEConsentForms.DeclarationSignatures DeclarationSignatures1;
        
        /// <summary>
        /// HdnPatientId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField HdnPatientId;
        
        /// <summary>
        /// HdnLocation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField HdnLocation;
    }
}
