//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsentFormInterface.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Treatment", Namespace="http://schemas.datacontract.org/2004/07/BethesdaConsentFormWCFSvc")]
    [System.SerializableAttribute()]
    public partial class Treatment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsentFormInterface.ServiceReference1.ConsentType _consentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsentFormInterface.ServiceReference1.DoctorAndPrcedure[] _doctorAndPrceduresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool _isPatientUnableSignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _patientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsentFormInterface.ServiceReference1.Signatures[] _signaturesesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsentFormInterface.ServiceReference1.TrackingInformation _trackingInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _translatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _unableToSignReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsentFormInterface.ServiceReference1.ConsentType _consentType {
            get {
                return this._consentTypeField;
            }
            set {
                if ((this._consentTypeField.Equals(value) != true)) {
                    this._consentTypeField = value;
                    this.RaisePropertyChanged("_consentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsentFormInterface.ServiceReference1.DoctorAndPrcedure[] _doctorAndPrcedures {
            get {
                return this._doctorAndPrceduresField;
            }
            set {
                if ((object.ReferenceEquals(this._doctorAndPrceduresField, value) != true)) {
                    this._doctorAndPrceduresField = value;
                    this.RaisePropertyChanged("_doctorAndPrcedures");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool _isPatientUnableSign {
            get {
                return this._isPatientUnableSignField;
            }
            set {
                if ((this._isPatientUnableSignField.Equals(value) != true)) {
                    this._isPatientUnableSignField = value;
                    this.RaisePropertyChanged("_isPatientUnableSign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _patientId {
            get {
                return this._patientIdField;
            }
            set {
                if ((object.ReferenceEquals(this._patientIdField, value) != true)) {
                    this._patientIdField = value;
                    this.RaisePropertyChanged("_patientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsentFormInterface.ServiceReference1.Signatures[] _signatureses {
            get {
                return this._signaturesesField;
            }
            set {
                if ((object.ReferenceEquals(this._signaturesesField, value) != true)) {
                    this._signaturesesField = value;
                    this.RaisePropertyChanged("_signatureses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsentFormInterface.ServiceReference1.TrackingInformation _trackingInformation {
            get {
                return this._trackingInformationField;
            }
            set {
                if ((object.ReferenceEquals(this._trackingInformationField, value) != true)) {
                    this._trackingInformationField = value;
                    this.RaisePropertyChanged("_trackingInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _translatedBy {
            get {
                return this._translatedByField;
            }
            set {
                if ((object.ReferenceEquals(this._translatedByField, value) != true)) {
                    this._translatedByField = value;
                    this.RaisePropertyChanged("_translatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _unableToSignReason {
            get {
                return this._unableToSignReasonField;
            }
            set {
                if ((object.ReferenceEquals(this._unableToSignReasonField, value) != true)) {
                    this._unableToSignReasonField = value;
                    this.RaisePropertyChanged("_unableToSignReason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackingInformation", Namespace="http://schemas.datacontract.org/2004/07/BethesdaConsentFormWCFSvc")]
    [System.SerializableAttribute()]
    public partial class TrackingInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _deviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _iPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _device {
            get {
                return this._deviceField;
            }
            set {
                if ((object.ReferenceEquals(this._deviceField, value) != true)) {
                    this._deviceField = value;
                    this.RaisePropertyChanged("_device");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _iP {
            get {
                return this._iPField;
            }
            set {
                if ((object.ReferenceEquals(this._iPField, value) != true)) {
                    this._iPField = value;
                    this.RaisePropertyChanged("_iP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsentType", Namespace="http://schemas.datacontract.org/2004/07/BethesdaConsentFormWCFSvc")]
    public enum ConsentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Surgical = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cardiovascular = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OutsideOR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Endoscopy = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BloodConsentOrRefusal = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlasmanApheresis = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PICC = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoctorAndPrcedure", Namespace="http://schemas.datacontract.org/2004/07/BethesdaConsentFormWCFSvc")]
    [System.SerializableAttribute()]
    public partial class DoctorAndPrcedure : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _preceduresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _primaryDoctorIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _precedures {
            get {
                return this._preceduresField;
            }
            set {
                if ((object.ReferenceEquals(this._preceduresField, value) != true)) {
                    this._preceduresField = value;
                    this.RaisePropertyChanged("_precedures");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _primaryDoctorId {
            get {
                return this._primaryDoctorIdField;
            }
            set {
                if ((object.ReferenceEquals(this._primaryDoctorIdField, value) != true)) {
                    this._primaryDoctorIdField = value;
                    this.RaisePropertyChanged("_primaryDoctorId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Signatures", Namespace="http://schemas.datacontract.org/2004/07/BethesdaConsentFormWCFSvc")]
    [System.SerializableAttribute()]
    public partial class Signatures : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string _signatureContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsentFormInterface.ServiceReference1.SignatureType _signatureTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _name {
            get {
                return this._nameField;
            }
            set {
                if ((object.ReferenceEquals(this._nameField, value) != true)) {
                    this._nameField = value;
                    this.RaisePropertyChanged("_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _signatureContent {
            get {
                return this._signatureContentField;
            }
            set {
                if ((object.ReferenceEquals(this._signatureContentField, value) != true)) {
                    this._signatureContentField = value;
                    this.RaisePropertyChanged("_signatureContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsentFormInterface.ServiceReference1.SignatureType _signatureType {
            get {
                return this._signatureTypeField;
            }
            set {
                if ((this._signatureTypeField.Equals(value) != true)) {
                    this._signatureTypeField = value;
                    this.RaisePropertyChanged("_signatureType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignatureType", Namespace="http://schemas.datacontract.org/2004/07/BethesdaConsentFormWCFSvc")]
    public enum SignatureType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DoctorSign1 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DoctorSign2 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DoctorSign3 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DoctorSign4 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DoctorSign5 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DoctorSign6 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DoctorSign7 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PatientSign = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PatientAuthorizeSign = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WitnessSignature1 = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WitnessSignature2 = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PICCSignature = 11,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ConsentFormSvc")]
    public interface ConsentFormSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsentFormSvc/AddTreatment", ReplyAction="http://tempuri.org/ConsentFormSvc/AddTreatmentResponse")]
        void AddTreatment(ConsentFormInterface.ServiceReference1.Treatment treatment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsentFormSvc/GetTreatment", ReplyAction="http://tempuri.org/ConsentFormSvc/GetTreatmentResponse")]
        ConsentFormInterface.ServiceReference1.Treatment GetTreatment(string patientId, ConsentFormInterface.ServiceReference1.ConsentType consentType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsentFormSvcChannel : ConsentFormInterface.ServiceReference1.ConsentFormSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsentFormSvcClient : System.ServiceModel.ClientBase<ConsentFormInterface.ServiceReference1.ConsentFormSvc>, ConsentFormInterface.ServiceReference1.ConsentFormSvc {
        
        public ConsentFormSvcClient() {
        }
        
        public ConsentFormSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsentFormSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsentFormSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsentFormSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddTreatment(ConsentFormInterface.ServiceReference1.Treatment treatment) {
            base.Channel.AddTreatment(treatment);
        }
        
        public ConsentFormInterface.ServiceReference1.Treatment GetTreatment(string patientId, ConsentFormInterface.ServiceReference1.ConsentType consentType) {
            return base.Channel.GetTreatment(patientId, consentType);
        }
    }
}
